#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)

if [[ -f "$DOKKU_ROOT/$APP/REDEPLOY" ]]; then
  REDEPLOY=$(cat "$DOKKU_ROOT/$APP/REDEPLOY" 2> /dev/null || /dev/null)
  URL=$(dokku url $APP)
  echo "-----> Re-deploying $REDEPLOY ..."
fi
